version: '3.2'
services:
  relaxator:
    image: alagiz/relaxator
    command: nginx -g "daemon off;"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          cpus: '0.1'
          memory: 10M
    ports:
      - "8083:80"